### ISSUE TITLE
How to speed up import_from_tsv when Preparing the data

### ISSUE THREAD

**Issue by zwqjoy** [facebookresearch/PyTorch-BigGraph#42] opened 2019-04-27 08:37 UTC
I have lots of tsv data (~800G), I found when I use import_from_tsv to process the data with on machine(data 40G), I took 4 hours.

So If it want to process 800G data.  The time will be 20 *4  80 hours ?
I donot know whether my machine (240G mem) can process the data.
And  It will take lots time.

If some thing wrong (for example: the data process is killed) . I need do this from the begin ?

**Comment by lerks** [comment] 2019-04-27 21:58
`import_from_tsv` is a simple demo converter, not designed with scale in mind. It does all the processing in Python, and keeps all the data in memory. I don't recommend you use it for such a large dataset. I'm afraid that your best approach here is to write your own converter. You can look at the `import_to_tsv` code to see what such a converter needs to do.

At this point, if you have your data in some higher-level format from which you extracted that TSV, you may even want to write your converter to consume that. TSV is a neat format but it has quite some issues with scalability, namely its lack of support for random access and thus for partial reads.

**Comment by zwqjoy** [comment] 2019-04-28 06:46
@lerks  thanks,  I have another question.
If I have 4 file(4 * 200G) ,  the machine mem not enough keep  all the data in memory.

Whether I can do:
      process  every file alone , and get the 4 output

And I merge the  files:

4 entity_count_all_0.txt file to one file (plus)
4 entity_count_all_1.txt file to one file (plus)
4 dictionary.json to one files


After do this, the go on dist training with all data

**Comment by lerks** [comment] 2019-04-29 14:19
What you suggested would only work if your four TSV files contained the edges of four totally disjoint graphs. But in that case you might as well run PBG once on each of them separately and get the same result.

If, instead, they are four subsets of edges of the same graph then you'll have to process them together to some degree. For example, the `entity_count_foo_42.txt` files are the counts of _distinct_ entities across _all_ these files. This is different than the sum of counts of distinct entities within each of these files. Basically, the main operation that needs to be done across all files together is assigning to each distinct entity a partition index and an offset within that partition. Once that is done, you can process each edge separately.

Here is how this could be done.
- You could do a first pass over the edgelist where, for each edge, you assign each of its endpoints (left- and right-hand side) to its partition. You keep a file for each partition where you just append the entity names (without deduplicating them or sorting them). This assignment should be done by hashing an entity's name and taking its modulo. (This means the assignment is deterministic, but if the hash function is good enough it should be pretty uniform). You also keep a file for each bucket and append the edge to it. This could look something like:
  ```python
  with open("edgelist.tsv", "rt") as tf:
      for line in tf:
          lhs_entity, rhs_entity, rel_type = line.split()
          lhs_part = hash(lhs_entity) % num_partitions
          rhs_part = hash(rhs_entity) % num_partitions
          with open("entities_%d.txt" % lhs_part, "at") as lhs_tf:
              lhs_tf.write("%s\n" % lhs_entity)
          with open("entities_%d.txt" % rhs_part, "at") as rhs_tf:
              rhs_tf.write("%s\n" % rhs_entity)
          with open("bucket_%d_%d.tsv" % (lhs_part, rhs_part), "at") as bucket_tf:
              bucket_tf.write("%s\t%s\t%s\n" % (lhs_entity, rhs_entity, rel))
  ```
- You read each file with the entity names, deduplicate them and put them in some order (any order), which will assign them an offset. For example:
  ```python
  for part in range(num_partitions):
      with open("entities_%d.txt", "rt") as tf:
          entities = {line.strip() for line in tf}
      with open("unique_entities_%d.txt", "wt") as tf:
          for entity in entities:
              tf.write("%s\n" % entity)
  ```
- Then you process each bucket and convert entity names to offsets.
  ```python
  for lhs_part in range(num_partitions):
      with open("unique_entities_%d.txt" % lhs_part, "rt") as tf:
          lhs_entities = {name.strip(): offset for offset, name in enumerate(tf)}
      for rhs_part in range(num_partitions):
          with open("unique_entities_%d.txt" % rhs_part, "rt") as tf:
              rhs_entities = {name.strip(): offset for offset, name in enumerate(tf)}
          with open("bucket_%d_%d.tsv" % (lhs_part, rhs_part), "rt") as in_tf, \
                  open("processed_%d_%d.tsv" % (lhs_part, rhs_part), "wt") as out_tf:
              for line in in_tf:
                  lhs_entity, rhs_entity, rel_type = line.split()
                  out_tf.write("%s\t%s\t%s\n" % (lhs_entities[lhs_offset], rhs_entities[rhs_offset], rel_type))
  ```

The above algorithm has a lower memory footprint, as the most it needs to keep in memory at any time are the entity names of the entities in the current bucket and this can be controlled (i.e., reduced) by increasing the number of partitions. On the other hand, using too many partitions means that in the final snippet the entity names will have to be loaded from disk more often, making it slower. You should keep the number of partitions to the lowest number that allows this calculation to fit in memory.

The above code is just a sketch, in particular it doesn't handle assigning indices to the relation types, it doesn't support unpartitioned entity types and, in fact, the last part could directly output the `.h5` file.

**Comment by lerks** [comment] 2019-05-20 15:15
I've been thinking again at how to make the importing from TSV and the preprocessing faster (which is a related but technically orthogonal issue to the one of limiting the memory footprint, which I addressed in my previous comment).

Python is quite slow as a language so, a "native" Python program, like the one we currently have or the one I sketched above, is definitely far from the fastest solution we can have. However, I'm inclined to think that in most cases the bottleneck is I/O bandwidth. If that's the case then even a faster program won't make much difference, as long as computation and I/O happen simultaneously. (I'm not sure we're currently doing that, but it wouldn't be hard).

If for some reasons one has a computation bottleneck, there's a few options to address it. I don't think we'll end up implementing them in the upstream code: because of what I just said, the payoff seems small, and there's bigger things we can dedicate our limited time towards.

One first idea is to use PyPy as an interpreter instead of CPython. I've hardly ever used PyPy but I know its JIT compiler should be suited to make computations like these faster. It's supposed to be almost a drop-in replacement, so it should be quite easy to try.

Another option is using NumPy as an "accelerator", having it do all the heavy lifting in optimized codepaths implemented in C. (This, through PyTorch, is exactly why we can afford to write all our code in Python with limited performance impact). However, NumPy and PyTorch are designed for array/tensor data, where each element has a fixed size and is neatly fitted in a grid. They are not great when it comes to variable-length strings, which is what we need here (we could use fixed-length strings, but I think the memory cost would be prohibitive as we need to allocate for each entity as much space as the longest entity name which, for example in the Wikidata dataset, is often much longer than the average one).

One last option is using standard UNIX high-performance tools for text manipulation. For this task in particular AWK seems extremely well suited. One would have to rewrite the pre-processing step in AWK's language but it appears to be relatively easy. (Note that there's several AWK implementations, some more optimized than others). I tried writing a quick program which only works for a single relation type (in fact, it ignores the relation type) and just splits the entities on both sides in 10 partitions. It is not designed for memory efficiency, so it could certainly be rewritten with some of the considerations of my previous comment to make it more efficient but more complex. Here's the code:
```awk
BEGIN {
    for (part_idx = 0; part_idx < 10; part_idx++) {
        part_size[part_idx] = 0
    }
}
{
    lhs_ent = $1
    rhs_ent = $2
    if (lhs_ent in entity_to_part) {
        lhs_part = entity_to_part[lhs_ent]
        lhs_offset = entity_to_offset[lhs_ent]
    } else {
	lhs_part = int(rand() * 10)
        entity_to_part[lhs_ent] = lhs_part
        lhs_offset = part_size[lhs_part]
        entity_to_offset[lhs_ent] = lhs_offset
        part_size[lhs_part]++
        print lhs_ent >> "entities_" lhs_part ".txt"
    }
    if (rhs_ent in entity_to_part) {
        rhs_part = entity_to_part[rhs_ent]
        rhs_offset = entity_to_offset[rhs_ent]
    } else {
	rhs_part = int(rand() * 10)
        entity_to_part[rhs_ent] = rhs_part
        rhs_offset = part_size[rhs_part]
        entity_to_offset[rhs_ent] = rhs_offset
        part_size[rhs_part]++
        print rhs_ent >> "entities_" rhs_part ".txt"
    }
    print lhs_part, lhs_offset, rhs_part, rhs_offset >> "partitioned_" FILENAME
}
```
It can be run as follows:
```sh
awk -f program edgelist_1.tsv edgelist_2.tsv
```
Once finished the data can be loaded into NumPy with the very efficient `fromfile` function:
```py
a = np.fromfile("partitioned_edgelist_1.tsv", dtype=np.int64, sep=" ").reshape((-1, 4))
```
And then dumped to a HDF5 file.

I hope these pointers can help anyone out that is struggling with a lot of data in TSV format and slow imports. If there's additional demand we can consider including some of these upstream.

**Comment by lerks** [comment] 2019-05-21 09:00
I there's a lot of material in this issue's discussion to work with if one needs to improve the performance of `import_from_tsv`. As I mentioned, I don't think I'll have time to do apply any of this to the upstream version in the near future. I'm closing this issue for the time being, I'll reopen it if this gets reprioritized.

**Closed by lerks** 2019-05-21 09:00 UTC

**Comment by rom1504** [comment] 2020-01-11 23:22
@lerks I am trying to reproduce the results of the paper on freebase big graph (only filtered with entities and relations appearing at least 5 times). I did regenerate the dataset (with some spark), and its size if about 300GB in tsv format.
Am I correct to assume that I will need to rewrite a memory efficient import_from_tsv ?
The current one seems indeed to put everything in memory, which doesn't fit here. Did you use another importer for this experiment or a big machine ?

I guess for this use case I would have to do something along these lines https://github.com/facebookresearch/PyTorch-BigGraph/issues/42#issuecomment-487598451 

(reproducing on freebase dataset is only my first step before applying PBG on another dataset which is about the same size)

**Comment by lerks** [comment] 2020-01-13 11:50
Yes, I don't think the `import_from_tsv` script that's shipped with PBG will work for you. Note however that you don't have to write a more efficient _TSV_ importer: since you're manipulating your data with Spark, I'm sure you already have it in a more efficient format, so you can write an importer that directly reads that format. What's more, you can do the partitioning and bucketing steps efficiently in Spark and so avoid doing them in the importer (or you could run your Spark pipeline as a step in the importer). You could also go one step further (which would however require a fair bit more work) and write a Spark EdgelistStorage (plus a EntityCountStorage and a RelationTypeCountStorage), to avoid any intermediate format completely.

In our experiments we did use other importers, which we didn't open-source because we've since changed the format of the data, from a hacky pickle dump to a more polished HDF5 file.

**Comment by rom1504** [comment] 2020-01-13 13:36
Ok thank you for the explanations, that makes sense. I'll try doing something like that
