### ISSUE TITLE
[Question] Are featurized entities supported on GPUs?

### ISSUE THREAD

**Issue by Ishitori** [facebookresearch/PyTorch-BigGraph#252] opened 2022-02-22 19:45 UTC
I am trying to train PBG model using featurized entities. It works fine on CPU, but I hope to use 8 GPUs to make training faster. I have about 1M features.

I setup the config, but when I launch the training I see the following logs:

```
2022-02-22 19:40:59,066   [Trainer-0] ( 0 , 0 ): Loading edges
2022-02-22 19:41:08,969      [GPU #2] GPU subprocess 2 up and running
2022-02-22 19:41:08,969      [GPU #6] GPU subprocess 6 up and running
2022-02-22 19:41:08,970      [GPU #4] GPU subprocess 4 up and running
2022-02-22 19:41:08,970      [GPU #5] GPU subprocess 5 up and running
2022-02-22 19:41:08,970      [GPU #3] GPU subprocess 3 up and running
2022-02-22 19:41:08,971      [GPU #0] GPU subprocess 0 up and running
2022-02-22 19:41:08,971      [GPU #7] GPU subprocess 7 up and running
2022-02-22 19:41:08,981      [GPU #1] GPU subprocess 1 up and running
2022-02-22 19:42:21,438   [Trainer-0] ( 0 , 0 ): Shuffling edges
2022-02-22 19:42:21,438   [Trainer-0] ( 0 , 0 ): Waiting for workers to perform training
2022-02-22 19:42:21,438   [Trainer-0] ( 0 , 0 ): Splitting edges into sub-buckets
corrupted size vs. prev_size
/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 4 leaked semaphores to clean up at shutdown
  len(cache))
```

Any ideas what went wrong? Is featurized entities feature supported on GPU at all?

**Comment by rkindi** [comment] 2022-02-22 20:48
@Ishitori, I asked @adamlerer about this and he said it's likely not supported.

**Comment by rkindi** [comment] 2022-02-24 14:06
Closing this as it's a duplicate of #237

**Closed by rkindi** 2022-02-24 14:06 UTC
