### ISSUE TITLE
How to train multi level relationship?

### ISSUE THREAD

**Issue by circlegao** [facebookresearch/PyTorch-BigGraph#193] opened 2021-03-08 07:47 UTC
I have 3 types of entities: A,B &C.

I want to have a multi level relationship like A->B->C

For example:

A             B         C
1             1.1       1.1.1
2             1.1       1.2.1
3             1.1       1.3.1
1             1.2       1.1.2
2             1.2       1.2.2
So the relation between entity type B and entity type C also depends on relation between entity type A & B.

Given an entity of type A & an entity of type B, we want to predict top 5 entities of type C.

How to structure this training data?

should we add B & C with BC relation and A &C with AC relation in training set? Or is there any other way to handle such cases?

**Comment by lw** [comment] 2021-03-08 08:37
Duplicate of https://github.com/facebookresearch/PyTorch-BigGraph/issues/167.

**Closed by lw** 2021-03-08 08:37 UTC

**Comment by circlegao** [comment] 2021-03-08 08:50
> Duplicate of #167.

yes, I don't find answer there , so what's the answer?

**Comment by lw** [comment] 2021-03-08 08:58
In such cases you should revive the discussion of that old issue, rather than copy-pasting the same text in a new issue.

If there's no answer it probably means no one knew how to deal with that. Each use case has its own quirks, and may not have a ready solution. I suggest you play around a bit, trying to come up with approaches and compare them, and possibly report back your results to help future users. Thanks!
