### ISSUE TITLE
Distributed job on slurm cluster fails with "RuntimeError: No route to host"

### ISSUE THREAD

**Issue by currymj** [facebookresearch/PyTorch-BigGraph#99] opened 2019-09-11 20:46 UTC
## Steps to reproduce

Run a distributed job on the FB15K example data, across two nodes on a cluster that uses the Slurm scheduler. (This would be hard to reproduce without access to such a cluster. The job submission scripts I used are below.)

I can confirm that this spawns two processes, each of which correctly knows their rank and the tcp initialization URL corresponding to the hostname and port of the rank 0 process.

I've checked that right before calling `torchbiggraph_train`, the machines can ping the master node, and I am reserving a range of open ports and using one of them for initialization. I'm not sure whether the `init_process_group` step is succeeding for any of the processes or not.

Some workarounds I have tried:

- lots of different ports
- manually specifying various network interfaces using the `GLOO_SOCKET_IFNAME` environment variable
- using a file for synchronization won't work due to limitations of the distributed filesystem

## Observed Results

Many of the processes quickly crash, all due to the same "RuntimeError: No route to host" error, which happens when trying to create a `TCPStore` object. They all look something like this:

```
Process ParameterServer-3:
Traceback (most recent call last):
  File "/state/partition1/llgrid/pkg/anaconda/anaconda3-2019a/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/state/partition1/llgrid/pkg/anaconda/anaconda3-2019a/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gridsan/mcurry/.local/lib/python3.6/site-packages/torchbiggraph/distributed.py", line 111, in _server_init
    groups=groups,
  File "/home/gridsan/mcurry/.local/lib/python3.6/site-packages/torchbiggraph/distributed.py", line 84, in init_process_group
    timeout=timeout)
  File "/state/partition1/llgrid/pkg/anaconda/anaconda3-2019a/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 354, in init_process_group
    store, rank, world_size = next(rendezvous(url))
  File "/state/partition1/llgrid/pkg/anaconda/anaconda3-2019a/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 95, in _tcp_rendezvous_handler
    store = TCPStore(result.hostname, result.port, world_size, start_daemon)
RuntimeError: No route to host
Process LockServer-6:
Traceback (most recent call last):
  File "/state/partition1/llgrid/pkg/anaconda/anaconda3-2019a/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/state/partition1/llgrid/pkg/anaconda/anaconda3-2019a/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gridsan/mcurry/.local/lib/python3.6/site-packages/torchbiggraph/distributed.py", line 111, in _server_init
    groups=groups,
  File "/home/gridsan/mcurry/.local/lib/python3.6/site-packages/torchbiggraph/distributed.py", line 84, in init_process_group
    timeout=timeout)
  File "/state/partition1/llgrid/pkg/anaconda/anaconda3-2019a/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 354, in init_process_group
    store, rank, world_size = next(rendezvous(url))
  File "/state/partition1/llgrid/pkg/anaconda/anaconda3-2019a/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 95, in _tcp_rendezvous_handler
    store = TCPStore(result.hostname, result.port, world_size, start_daemon)
RuntimeError: No route to host
Traceback (most recent call last):
  File "/home/gridsan/mcurry/.local/lib/python3.6/site-packages/torchbiggraph/parameter_sharing.py", line 334, in _client_thread_loop
    groups=groups,
  File "/home/gridsan/mcurry/.local/lib/python3.6/site-packages/torchbiggraph/distributed.py", line 84, in init_process_group
    timeout=timeout)
  File "/state/partition1/llgrid/pkg/anaconda/anaconda3-2019a/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 354, in init_process_group
    store, rank, world_size = next(rendezvous(url))
  File "/state/partition1/llgrid/pkg/anaconda/anaconda3-2019a/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 95, in _tcp_rendezvous_handler
    store = TCPStore(result.hostname, result.port, world_size, start_daemon)
RuntimeError: No route to host
```

## Expected Results

Ideally, a running distributed training process.

## Relevant Code

```
#!/bin/bash
#SBATCH --ntasks 2
#SBATCH -N 2
#SBATCH --job-name=distributed-pbg
#SBATCH -o log-distributed-%j.out

source /etc/profile

export HDF5_USE_FILE_LOCKING='FALSE'
export PARENT=`/bin/hostname -s`
#export MPORT=13001
export CHILDREN=`scontrol show hostnames $SLURM_JOB_NODELIST | grep -v $PARENT`
export HOSTLIST="$PARENT $CHILDREN"
echo $HOSTLIST
export WORLD_SIZE=$SLURM_NTASKS

srun --resv-ports=30 ./distributed_runner.sh
```

where distributed_runner.sh is:
```
#!/bin/bash

export MPORT=`echo $SLURM_STEP_RESV_PORTS | cut -d- -f1`
echo $MPORT
torchbiggraph_train --rank $SLURM_PROCID fb15k_config_distributed.py -p edge_paths=data/FB15k/freebase_mtr100_mte100-train_partitioned
```

Other questions include:

- There are a lot of different processes running; is it possible that some of them are trying to communicate on default ports that might be closed or in use for some reason?

- What types of situations was PBG distributed mode originally designed to work in? Is there kind of an implicit assumption that it's going to be run on a bunch of VPSs on one of the cloud providers?

I would really appreciate any help or even just vague intuition on how we might try to get this working on a cluster (I suspect other people in academic environments will eventually run into similar problems). It is already churning away in non-distributed mode, but our graph really is big and it would be good to parallelize as we tune hyperparameters.

**Comment by lerks** [comment] 2019-09-13 13:17
I have personally never run it on Slurm, so I may me missing something here. PBG isn't doing anything special regarding Gloo's rendezvous. We do however spawn multiple processes per machine, and have them all connect to each other. Two issues that could be at play here are that either there's not enough open ports on a machine for all the processes that we start there (this would be odd, because we only start up to 5 I think), another option is that the machine is having troubles "connecting to itself" (even odder).

It would help a lot if you could try to set up a small demo with two machines, each spawning a subprocesses, and all 4 of these processes (2 parents + 2 children) connecting using Gloo. If that also fails then the issue is in PyTorch or Gloo and you should open a task there. On the other hand if that works then we'll have to look into what PBG is doing that is different from that example.

**Comment by currymj** [comment] 2019-09-13 18:26
That turned out to be good advice. I had tested some smaller pytorch distributed examples, but none of them spawned multiple processes per slurm task.

Using [this](https://gist.github.com/currymj/34e9c949225512c89862a76356e74519), which spawns multiple processes, I was able to recreate the problem. In at least one case I got the same `No route to host`; in other cases the processes simply hung or timed out.

Interestingly, by changing the `size` variable to 1 in the same code, I can make it so that there is only one process per slurm task. And then everything works perfectly.

Is the regular Pytorch repository the place to file an issue about this?

**Comment by lerks** [comment] 2019-09-13 18:31
I guess the Pytorch repo would be a good place to start to ask help for this. They may reroute you to the Gloo people, if that's the root cause, or maybe even to Slurm if it is setting up the environment incorrectly. I hope you can get your issue fixed!

**Comment by currymj** [comment] 2019-09-13 18:37
Actually, never mind -- there was a bug in my test code (which I've checked does not exist in the original PBG stuff). Having fixed it (updated gist) things now seem to run perfectly.

**Comment by lerks** [comment] 2019-09-21 20:12
So you're saying that in the end you were _not_ able to reproduce it with your demo? I looked at your code and couldn't find anything wrong. So let's try to get it to match closer what PBG is doing.

One first thing to try is to launch processes using the "spawn" method (the default is "fork"). This can be achieved by calling `mp.get_context("spawn").Process(...)`. This has a few difference in how the state is passed along to children, including at times environment variables.

Another difference (which is probably irrelevant but let's check it out anyways) is that in PBG the "root" process on each machine also participates in the distributed group.

What's more, each of the root processes is _also_ part of a different "subgroup". In practice this means that _all_ processes (roots and children) call `torch.distributed.new_group` with the ranks of the root processes.

It may also be worth actually sending data around. You could make the (global) rank zero process behave like a echo server that goes round-robin over all others, recvs and sends back the result. (All other processes would send something, recv it back and then terminate).

If nothing of this works, we'll see what we can do further...

**Comment by currymj** [comment] 2019-09-22 18:47
Firstly, thanks for all your time and thoughtful advice so far. I will try to lay out everything I’ve done below in a very detailed way.

The executive summary is:

- In the example code, it seems like the `No route to host` error shows up only when the rank \>0 processes call `init_process_group` before the rank 0 process has done so. This sometimes happens but, for my example code, it can be prevented.
- I don’t know whether that is expected behavior of `torch.distributed` when using TCP initialization or not.
- I think this also might be the cause of the problem when running PBG but haven’t confirmed that. I don’t know how to ensure that the rank 0 process in PBG has initialized before any of the others.

I also have some concrete questions at the bottom.

## Initial bug in my example code

I had a silly bug in the first version of my example code. I was forgetting to parse an environment variable from string to int — this resulted in later computing a `world_size` of `’2’ + 2`, with a result of `’22’` instead of `4`, causing processes to hang.

I reported that I had reproduced the problem, but then caught and fixed this bug, and my example code seemed to work.

## Race condition

After fixing that problem, I thought everything was working (meaning I could not reproduce the bug) — was able to run code many times and see working results.

However, when re-trying things today, I got the same “No route to host” error, maybe about 1/5 of times I tried to run. It seems that although the scheduler usually starts the parent job first, or at least fast enough, sometimes it doesn’t, and for whatever reason that is somewhat more likely today.

By forcing the parent job to sleep for a while before invoking python, I was able to make this error occur consistently. By forcing the child job to sleep before invoking python, I was able to prevent it consistently.

I was optimistic that this would be a simple fix for the problem — unfortunately, when applied to the PBG code, it doesn’t seem to help. I still see a “No route to host” error, from processes (I think the `LockServer` usually) that come from the rank 0 invocation of `torchbiggraph_train`, and are all running on the same physical node.

## Results of recommended modifications to example code:


While ensuring that the rank 0 process ran first, I tried the suggested modifications to the code, and they all apparently worked fine.

- Using “spawn” instead of just creating a process normally doesn’t seem to matter — example code still works fine.
- Letting the root process also call `init_process_group` and run in the example code also seems to work fine.
- Putting both root processes in a separate group also seems to work fine.
- calling send and recv also appears to work fine, going both ways.

(Note that I just kept tacking on each of those modifications —  so I didn’t try sending/receiving data but without using spawn, and things like that. But I don’t think this should make a difference.)

## More on race condition

- I was able to put delays within the Python code (not just calling “sleep” from bash), which makes it clear that `init_process_group` on rank 0 must actually be invoked — it’s not enough to just have the process running.
- Race condition persists even when using `spawn`.

## Questions

I don’t see anything in the `torch.distributed` documentation saying that you absolutely must ensure that the rank 0 process has initialized before any other process calls `init_process_group`. Is this actually a requirement, or is it perhaps due to some weird configuration on this cluster?

Within PyTorch-BigGraph, I see that the actual rank of each process is determined by a `ProcessRanks` class. Is there a way to know which process actually gets rank 0, and somehow ensure that it’s definitely running before the others?

**Comment by lerks** [comment] 2019-09-24 21:12
Thanks for the amazing investigation! It really provides a lot of answers.

I had never heard of issues in distributed training caused by the rank 0 process coming up after the others, nor did other people I asked. Moreover the error "no route to host" indicate that the rank 0 process's address isn't in the routing table, which is a very odd error. My guess is that your cluster configuration is a bit odd and is perhaps building the routing table dynamically as hosts bind to the addresses.

It could be possible to delay all non-rank-0 processes in PBG, to increase the chance that the rank-0 one starts first, but it poses several problems. (Rank 0 is given to the root process of trainer 0). The main issue is that the solution is brittle: it will help reduce the probability of this happening (the higher the delay the smaller the probability) but it won't eliminate the race condition.

From what you said I understand that you've been able to replicate the problem in your demo, by delaying the rank 0 initialization. The silver lining in this is that we've ruled out that PBG is at fault, so I suggest that you reach out to either the PyTorch or the Gloo people to see if they have seen such a problem before. You may also want to reach out to your cluster's admins (or to the Slurm maintainers if you're managing your own cluster) to see if it's misconfigured somehow.

Let me know if you think there's something more PBG could do here.

**Comment by currymj** [comment] 2019-09-25 00:58
Probably not -- I may ultimately end up trying just adding `time.sleep(30)` to a bunch of constructors to slow down initialization, but obviously that's a pretty bad solution. I had initially imagined just making the root process call `init_process_group` before spawning the servers, but that won't work because it blocks while waiting for all the others, which won't have been started yet.

I have opened an issue in the Gloo repository and will also ask the cluster admins what their thoughts are.

I really appreciate all your help here, especially since it ended up not being a PBG-specific bug.

**Comment by lerks** [comment] 2019-10-15 14:18
So, we've determined that this issue can be reproduced in "plain" PyTorch and that it's not PBG-specific, and that it appears to be caused by an odd network setup in your cluster. We could add mitigations to PBG for this specific issue, but (apart from just reducing the probability of the condition, without removing it entirely), it seems more appropriate to fix the root cause instead. Thus I'm closing this.

**Closed by lerks** 2019-10-15 14:18 UTC

**Comment by mralexisw** [comment] 2019-11-23 21:30
@currymj Out of curiosity, would it be possible to share your config file for the distributed training?
