### ISSUE TITLE
Is the result of ComplEx model on FB15K reproducible?

### ISSUE THREAD

**Issue by yangapku** [facebookresearch/PyTorch-BigGraph#18] opened 2019-04-04 11:50 UTC
Hi, I made an attempt to reproduce the result on FB15K mentioned in the README. However, the result on testset was much lower than what is mentioned in README. The FB15K dataset I used was downloaded from the link in README and the command and config file (`examples/configs/fb15k_config.py`) were just the same as in the repo. The training was finished on a single machine. Could you please figure out this issue?

**Comment by lerks** [comment] 2019-04-04 12:03
The only way to exactly reproduce the metrics in the paper is to use the `examples/fb15k.py` script. That is because that script uses a "special" evaluation method (_filtered_ MRR), whereas the standard `torchbiggraph_eval` command used _unfiltered_ MRR. There's no way to have `torchbiggraph_eval` do filtered MRR as it doesn't scale.

Just to clarify: the training you performed did probably produce good embeddings, as good as in the paper, it's just that the evaluation didn't capture this.

You can still use `examples/fb15k.py` to perform the evaluation on the embeddings you learned: if you put it in the right location (see README) the script will detect and use it rather than re-train from scratch.

I'm closing this but feel free to reopen if I got anything wrong or if you're still facing issues.

**Closed by lerks** 2019-04-04 12:03 UTC
